FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

# use this Dockerfile to install additional tools you might need, e.g.
RUN git config --global user.email "16567092+farahbrunache@users.noreply.github.com" \
	&& git config --global user.name "farahbrunache"
